#:kivy 2.3

<SettingsPopup>:
  title: ""
  size_hint: 0.7, 0.35
  auto_dismiss: True

  BoxLayout:
    orientation: "vertical"
    padding: '12dp'
    spacing: '8dp'

    CustomButton:
      text: "Download Backup"
      size_hint_y: None
      height: '48dp'
      background_normal: ""
      background_color: 0.2, 0.5, 0.8, 1
      on_release: root.trigger_backup()

    CustomLabel:
      text: "Settings"
      size_hint_y: None
      height: '32dp'
      color: 1.0, 1.0, 1.0, 1
