#:kivy 2.3

<CesarVaultApp>:
  font_name: "Roboto"

<CustomLabel@Label>:
  font_size: 16
  color: 0.9, 0.9, 0.9, 1

<CustomButton@Button>:
  font_size: 16
  background_normal: ""
  background_color: 0.2, 0.5, 0.8, 1
  color: 1, 1, 1, 1
  size_hint_y: None
  height: 48

<CustomTextInput@TextInput>:
  font_size: 20
  background_color: 0.15, 0.15, 0.15, 1
  foreground_color: 0.95, 0.95, 0.95, 1
  cursor_color: 0.8, 0.8, 0.8, 1
