#:kivy 2.3
#:import platform kivy

<CesarVaultApp>:
  font_name: "Roboto"

<CustomLabel@Label>:
  font_size: '16sp'
  color: 1.0, 1.0, 1.0, 1

<CustomButton@Button>:
  font_size: '16sp'
  background_normal: ""
  background_color: 0.2, 0.5, 0.8, 1
  color: 1.0, 1.0, 1.0, 1
  size_hint_y: None
  height: '48dp'

<CustomTextInput@TextInput>:
  font_size: '20sp'
  background_color: 0.15, 0.15, 0.15, 1
  foreground_color: 1.0, 1.0, 1.0, 1
  cursor_color: 0.8, 0.8, 0.8, 1
  keyboard_mode: 'managed' if platform == 'android' else 'auto'
  input_type: 'text'
